const jokes = [
  "Why don't scientists trust atoms? Because they make up everything!",
  "What's the best thing about Switzerland? I don't know, but the flag is a big plus.",
  "Did you hear about the mathematician who's afraid of negative numbers? He'll stop at nothing to avoid them.",
  "I used to play piano by ear, but now I use my hands.",
  "Why don't skeletons fight each other? They don't have the guts.",
  "Why did the scarecrow win an award? Because he was outstanding in his field.",
  "I'm reading a book about anti-gravity. It's impossible to put down!",
  "How do you organize a space party? You 'planet'!",
  "What do you call a fish wearing a crown? King Neptune.",
  "I bought shoes from a drug dealer. I don't know what he laced them with, but I've been tripping all day.",
  "Why don't eggs tell jokes? They might crack up.",
  "Why did the bicycle fall over? It was two-tired.",
  "What's orange and sounds like a parrot? A carrot.",
  "How does a penguin build its house? Igloos it together.",
  "Why don't scientists trust atoms? Because they make up everything!",
  "Why couldn't the leopard play hide-and-seek? Because he was always spotted.",
  "What do you call a pile of cats? A meowtain.",
  "Why don't skeletons fight each other? They don't have the guts.",
  "Why don't melons get married? Because they can't elope.",
  "What did the grape say when it got stepped on? Nothing, it just let out a little wine.",
  "What did one wall say to the other wall? I'll meet you at the corner.",
  "I told my wife she should embrace her mistakes. She hugged me.",
  "Why did the golfer bring two pairs of pants? In case he got a hole in one.",
  "What do you call fake spaghetti? An impasta.",
  "How do you organize a space party? You 'planet'!",
  "What's a chicken's favorite composer? Bach.",
  "Why did the scarecrow win an award? Because he was outstanding in his field.",
  "How do you catch a squirrel? Climb a tree and act like a nut.",
  "What do you get if you cross a snowman and a vampire? Frostbite.",
  "Why did the tomato turn red? Because it saw the salad dressing.",
  "What do you call a fish wearing a crown? King Neptune.",
  "I bought shoes from a drug dealer. I don't know what he laced them with, but I've been tripping all day.",
  "Why don't eggs tell jokes? They might crack up.",
  "Why did the bicycle fall over? It was two-tired.",
  "What do you call a snowman with a six-pack? An abdominal snowman.",
  "How does a penguin build its house? Igloos it together.",
  "Why don't scientists trust atoms? Because they make up everything!",
  "What do you get when you cross a snowman and a vampire? Frostbite.",
  "What did one hat say to the other hat? You stay here, I'll go on ahead.",
  "I'm reading a book about anti-gravity. It's impossible to put down!",
  "Why did the tomato turn red? Because it saw the salad dressing.",
  "How do you catch a squirrel? Climb a tree and act like a nut.",
  "What do you call fake spaghetti? An impasta.",
  "Why did the golfer bring two pairs of pants? In case he got a hole in one.",
  "What do you call a snowman with a six-pack? An abdominal snowman.",
  "What do you call a pile of cats? A meowtain.",
  "Why don't melons get married? Because they can't elope.",
  "What did one hat say to the other hat? You stay here, I'll go on ahead.",
  "What do you call a cow with no legs? Ground beef.",
  "How do you organize a space party? You 'planet'!",
  "Why did the bicycle fall over? It was two-tired.",
  "What's orange and sounds like a parrot? A carrot.",
  "How do you catch a squirrel? Climb a tree and act like a nut.",
  "What do you get if you cross a snowman and a vampire? Frostbite.",
  "Why did the tomato turn red? Because it saw the salad dressing.",
  "What do you call a fish wearing a crown? King Neptune.",
  "I bought shoes from a drug dealer. I don't know what he laced them with, but I've been tripping all day.",
  "Why don't eggs tell jokes? They might crack up.",
  "What did one wall say to the other wall? I'll meet you at the corner.",
  "I told my wife she should embrace her mistakes. She hugged me.",
  "Why did the golfer bring two pairs of pants? In case he got a hole in one.",
  "What do you call fake spaghetti? An impasta.",
  "How do you organize a space party? You 'planet'!",
  "What's orange and sounds like a parrot? A carrot.",
  "Why did the scarecrow win an award? Because he was outstanding in his field.",
  "How do you catch a squirrel? Climb a tree and act like a nut.",
  "What do you get if you cross a snowman and a vampire? Frostbite.",
  "Why did the tomato turn red? Because it saw the salad dressing.",
  "What do you call a fish wearing a crown? King Neptune.",
  "I bought shoes from a drug dealer. I don't know what he laced them with, but I've been tripping all day.",
  "Why don't eggs tell jokes? They might crack up.",
  "Why did the bicycle fall over? It was two-tired.",
  "What do you call a snowman with a six-pack? An abdominal snowman.",
  "How does a penguin build its house? Igloos it together.",
  "Why don't scientists trust atoms? Because they make up everything!",
  "What do you get when you cross a snowman and a vampire? Frostbite.",
  "What did one hat say to the other hat? You stay here, I'll go on ahead.",
  "I'm reading a book about anti-gravity. It's impossible to put down!",
  "Why did the tomato turn red? Because it saw the salad dressing.",
  "How do you catch a squirrel? Climb a tree and act like a nut.",
  "What do you call fake spaghetti? An impasta.",
  "Why did the golfer bring two pairs of pants? In case he got a hole in one.",
  "What do you call a snowman with a six-pack? An abdominal snowman.",
  "What do you call a pile of cats? A meowtain.",
  "Why don't melons get married? Because they can't elope.",
  "What did one hat say to the other hat? You stay here, I'll go on ahead.",
  "Why don't skeletons fight each other? They don't have the guts.",
  "What do you call a cow with no legs? Ground beef.",
  "Why don't eggs tell jokes? They might crack up.",
  "What did one wall say to the other wall? I'll meet you at the corner.",
  "I told my wife she should embrace her mistakes. She hugged me.",
  "Why did the golfer bring two pairs of pants? In case he got a hole in one.",
  "What do you call fake spaghetti? An impasta.",
  "How do you organize a space party? You 'planet'!",
  "What's orange and sounds like a parrot? A carrot.",
  "Why did the scarecrow win an award? Because he was outstanding in his field.",
  "How do you catch a squirrel? Climb a tree and act like a nut.",
  "What do you get if you cross a snowman and a vampire? Frostbite.",
  "Why did the tomato turn red? Because it saw the salad dressing.",
  "What do you call a fish wearing a crown? King Neptune.",
  "I bought shoes from a drug dealer. I don't know what he laced them with, but I've been tripping all day.",
  "Why don't eggs tell jokes? They might crack up.",
  "Why did the bicycle fall over? It was two-tired.",
  "What do you call a snowman with a six-pack? An abdominal snowman.",
  "How does a penguin build its house? Igloos it together.",
  "Why don't scientists trust atoms? Because they make up everything!",
  "What do you get when you cross a snowman and a vampire? Frostbite.",
  "What did one hat say to the other hat? You stay here, I'll go on ahead.",
];


function generateRandomJoke() {
  const randomIndex = Math.floor(Math.random() * jokes.length);
  return jokes[randomIndex];
}


function displayRandomJoke() {
  const r = document.getElementById("ran");
  const randomJoke = generateRandomJoke();
  ran.textContent = randomJoke;
}
